version: "3.9"

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_MODEL=gpt-3.5-turbo
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - TOP_K=3
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
